pipeline {
    agent any

    environment {
        RELEASE = '0.0.1'
    }

    stages {
        stage('Build') {
            environment {
                LOG_LEVEL = 'info'
            }

            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL} ..."
            }
        }
    
        stage('Test') {
            steps {
                echo "Testing. I can see release ${RELEASE}, but nog log level"
            }
        }
    
        stage('Deploy') {
            input {
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
                }
            }
            steps {
                echo "Deploying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
            }
        }
    
    
    }
}