pipeline {
    agent any

    environment {
        RELEASE = '0.0.1'
    }

    stages {
        stage('Build') {
            environment {
                LOG_LEVEL = 'info'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL} ..."
            }
        }
        stage('Test') {
            steps {
                echo "Testing. I can see release ${RELEASE}, but not log level ${LOG_LEVEL}"
            }
        }
    }
}