library identifier: 'jenkins-sessions-library@main', retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/hardcode83/jenkins-sessions-library.git'])

pipeline {
    agent any

    stages {
        stage('Audit tools'){
            steps {
                auditTools()
            }
        }

    }
}